blogTitle = "Blog by A. Shelepenok"
authorName = "Alexander Shelepenok"

blogDescr = "Hi. I solve problems related to internet projects development and optimization."
twitter = "https://twitter.com/truewpioneer"
github = "https://github.com/wpioneer"
vk = "https://vk.com/wpioneer"
rss = "/feed.xml"
telegram = "telegram:wpioneer"
email = "maito:a.shelepenok@gmail.com"