blogUrl = "http://ashk.io/"
blogLogoUrl = "http://ashk.io/logo.png"
blogUploadsUrl  = "http://ashk.io/content/"

blogTitle = "ASHK.IO"
blogAuthor = "Alexander Shelepenok"
blogDescr = "Hi. I'm a Software Engineer focused on Front End Development."

blogTwitterUrl = "https://twitter.com/truewpioneer"
blogGithubUrl = "https://github.com/wpioneer"
blogVkUrl = "https://vk.com/wpioneer"
blogRssUrl = "/feed.xml"
blogTelegramUrl = "telegram:wpioneer"
blogEmailUrl = "mailto:a.shelepenok@gmail.com"