blogTitle = "A. Shelepenok Blog"
authorName = "Alexander Shelepenok"
linkPrefix = "/gatsby-starter-blog"
blogDescr = "Привет! Решаю вопросы связанные с разработкой и оптимизацией интернет-проектов."
twitter = "#"
github = "#"
vk = "#"
rss = "#"
telegram = "#"
email = "#"