blogTitle = "My Awesome Blog"
authorName = "Kyle Mathews"
linkPrefix = "/gatsby-starter-blog"
blogDescr = "Novelist is a minimal theme for writers. It makes your content nice and easy to read."
blogBg = ""
twitter = ""
github = ""
vk = ""
rss = ""