blogTitle = "Alexander Shelepenok"
authorName = "Alexander Shelepenok"
contentUrl = "http://ashk.io/content/"

blogDescr = "Hi. I solve problems related to internet projects development and optimization."
twitter = "https://twitter.com/truewpioneer"
github = "https://github.com/wpioneer"
vk = "https://vk.com/wpioneer"
rss = "/feed.xml"
telegram = "telegram:wpioneer"
email = "mailto:a.shelepenok@gmail.com"