blogTitle = "Blog by A. Shelepenok"
authorName = "Alexander Shelepenok"
linkPrefix = "/gatsby-starter-blog"
blogDescr = "Привет! Решаю вопросы связанные с разработкой и оптимизацией интернет-проектов."
twitter = "https://twitter.com/truewpioneer"
github = "https://github.com/wpioneer"
vk = "https://vk.com/wpioneer"
rss = "/feed.xml"
telegram = "telegram:wpioneer"
email = "maito:a.shelepenok@gmail.com"